In [2]:
import polars as pl

In [3]:
df = pl.read_csv(
    "/project/logsdon_shared/projects/Keith/NucFlagPaper/workflow/scripts/metrics/out.csv",
    null_values=["None"],
).with_columns(is_small=pl.col("len").is_in([1, 2, 10, 100]))
df

shape: (378, 11)
┌─────────────┬────────┬────────────┬─────────────┬───┬───────────┬──────────┬──────────┬──────────┐
│ tool        ┆ sample ┆ downsample ┆ dtype       ┆ … ┆ precision ┆ recall   ┆ f1       ┆ is_small │
│ ---         ┆ ---    ┆ ---        ┆ ---         ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ str         ┆ str    ┆ f64        ┆ str         ┆   ┆ f64       ┆ f64      ┆ f64      ┆ bool     │
╞═════════════╪════════╪════════════╪═════════════╪═══╪═══════════╪══════════╪══════════╪══════════╡
│ HMM-Flagger ┆ HG002  ┆ 0.33       ┆ PacBio HiFi ┆ … ┆ 0.504439  ┆ 0.132979 ┆ 0.210473 ┆ true     │
│ v1.1.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
│ HMM-Flagger ┆ HG002  ┆ 0.33       ┆ ONT R10     ┆ … ┆ 0.691176  ┆ 0.05     ┆ 0.093254 ┆ true     │
│ v1.1.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
│ HMM-Flagger ┆ HG002  ┆ 0.33       ┆ PacBio HiFi ┆ … ┆ 0.512434  ┆ 0.144681 ┆ 0.225651 ┆ true     │
│ v1.1.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
│ HMM-Flagger ┆ HG002  ┆ 0.33       ┆ ONT R10     ┆ … ┆ 0.626344  ┆ 0.049574 ┆ 0.091877 ┆ true     │
│ v1.1.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
│ HMM-Flagger ┆ HG002  ┆ 0.33       ┆ PacBio HiFi ┆ … ┆ 0.486411  ┆ 0.148511 ┆ 0.227547 ┆ true     │
│ v1.1.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
│ …           ┆ …      ┆ …          ┆ …           ┆ … ┆ …         ┆ …        ┆ …        ┆ …        │
│ NucFlag     ┆ HG002  ┆ null       ┆ ONT R10     ┆ … ┆ 0.3171009 ┆ 0.727609 ┆ 0.441702 ┆ false    │
│ v1.0.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
│ NucFlag     ┆ HG002  ┆ null       ┆ PacBio HiFi ┆ … ┆ 0.097543  ┆ 0.958913 ┆ 0.177074 ┆ false    │
│ v1.0.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
│ NucFlag     ┆ HG002  ┆ null       ┆ ONT R10     ┆ … ┆ 0.183033  ┆ 0.941304 ┆ 0.306473 ┆ false    │
│ v1.0.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
│ NucFlag     ┆ HG002  ┆ null       ┆ PacBio HiFi ┆ … ┆ 0.032748  ┆ 0.927391 ┆ 0.063262 ┆ false    │
│ v1.0.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
│ NucFlag     ┆ HG002  ┆ null       ┆ ONT R10     ┆ … ┆ 0.146672  ┆ 0.944565 ┆ 0.253915 ┆ false    │
│ v1.0.0      ┆        ┆            ┆             ┆   ┆           ┆          ┆          ┆          │
└─────────────┴────────┴────────────┴─────────────┴───┴───────────┴──────────┴──────────┴──────────┘

In [8]:
df_summ = (
    df.group_by(["dtype", "tool", "is_small"])
    .agg(
        pl.col("precision").mean(),
        pl.col("recall").mean(),
        pl.col("f1").mean(),
    )
    .sort("tool", "dtype")
)
df_summ

shape: (12, 6)
┌─────────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┐
│ dtype       ┆ tool               ┆ is_small ┆ precision ┆ recall   ┆ f1       │
│ ---         ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      │
│ str         ┆ str                ┆ bool     ┆ f64       ┆ f64      ┆ f64      │
╞═════════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╡
│ ONT R10     ┆ HMM-Flagger v1.1.0 ┆ true     ┆ 0.721197  ┆ 0.060183 ┆ 0.108733 │
│ ONT R10     ┆ HMM-Flagger v1.1.0 ┆ false    ┆ 0.42451   ┆ 0.315451 ┆ 0.326574 │
│ PacBio HiFi ┆ HMM-Flagger v1.1.0 ┆ true     ┆ 0.586317  ┆ 0.204941 ┆ 0.278494 │
│ PacBio HiFi ┆ HMM-Flagger v1.1.0 ┆ false    ┆ 0.49138   ┆ 0.782866 ┆ 0.577694 │
│ ONT R10     ┆ Inspector v1.3     ┆ true     ┆ 0.341888  ┆ 0.613948 ┆ 0.423845 │
│ …           ┆ …                  ┆ …        ┆ …         ┆ …        ┆ …        │
│ PacBio HiFi ┆ Inspector v1.3     ┆ true     ┆ 0.616032  ┆ 0.621087 ┆ 0.584969 │
│ ONT R10     ┆ NucFlag v1.0.0     ┆ true     ┆ 0.383081  ┆ 0.627642 ┆ 0.456661 │
│ ONT R10     ┆ NucFlag v1.0.0     ┆ false    ┆ 0.298766  ┆ 0.94806  ┆ 0.415371 │
│ PacBio HiFi ┆ NucFlag v1.0.0     ┆ true     ┆ 0.661105  ┆ 0.808197 ┆ 0.709938 │
│ PacBio HiFi ┆ NucFlag v1.0.0     ┆ false    ┆ 0.376111  ┆ 0.957729 ┆ 0.462139 │
└─────────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┘

In [10]:
df_summ.write_csv("summ.csv")